#!/bin/bash -norc
#$Id: datetime,v 1.1 2004/11/01 00:22:48 rogerms Exp $

#Description:
# This script displays the current date/time

#Usage:
# datetime

dd=`date +"%a %e %b"`
tt=`date +"%H:%M"`

echo "$dd" ; echo "    $tt"

#$Log: datetime,v $
#Revision 1.1  2004/11/01 00:22:48  rogerms
#Initial revision
#
#Revision 1.1  2004/09/09 13:25:37  RogerSeguin
#Initial revision
#
