#!/bin/bash -norc
#$Id: dkspuse,v 1.1 2004/11/01 00:22:48 rogerms Exp $

#Description#
# This script displays the space usage for each of the indicated partitions

if [ $# -eq 0 ]; then
	echo "" 1>&2
	exit 255
fi

Capacity ()
{
	capacity=`df -kP $1 | awk '{print $5;}'`
	capacity=`echo $capacity | awk '{print $2;}' | cut -d '%' -f 1`
	echo "${capacity}%"
} 

for partition in $*; do
	Capacity $partition
done

#$Log: dkspuse,v $
#Revision 1.1  2004/11/01 00:22:48  rogerms
#Initial revision
#
#Revision 1.2  2004/09/10 23:20:10  RogerSeguin
#Slight improvement
#
#Revision 1.1  2004/09/10 11:00:20  RogerSeguin
#Initial revision
#
